class CoinSerializer < ActiveModel::Serializer
  attributes  :id,
              :coingecko_id,
              :name,
              :symbol,
              :image,
              :current_price,
              :market_cap,
              :total_volume,
              :high_24h,
              :low_24h,
              :price_change_24h,
              :market_cap_change_24h,
              :market_cap_change_percentage_24h,
              :circulating_supply,
              :total_supply,
              :max_supply,
              :ath,
              :ath_change_percentage,
              :ath_date,
              :atl,
              :atl_change_percentage,
              :atl_date,
              :price_change_percentage_1h_in_currency,
              :price_change_percentage_24h_in_currency,
              :price_change_percentage_7d_in_currency,
              :last_updated
end
